openapi: 3.1.0
info:
  title: HTTP Bingo API
  version: "1.0.0"
servers:
  - url: https://httpbingo.org
paths:
  /get:
    get:
      summary: GET method for /get endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponse'
components:
  schemas:
    GetResponse:
      type: object
      properties:
        url:
          type: string
          example: "https://httpbingo.org/get"
