openapi: 3.1.0
info:
  title: My Service
  version: "1.0.0"
servers:
  - url: http://localhost:{port}
    description: local
    variables:
      port:
        default: '8080'
        description: The port number the server is running on
tags:
  - name: user
  - name: store
paths:
  /user:
    get:
      summary: GET User
      tags:
        - user
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /store:
    get:
      summary: GET Store
      tags:
        - store
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    Store:
      type: object
      properties:
        name:
          type: string
      required:
        - name
